export const mockModules = [
  {
    id: "1",
    title: "Inteligência Emocional no Trabalho",
    duration: "2 horas",
    level: "Iniciante",
    status: "not_started" as const,
    category: "Soft Skills",
    description: "Aprenda a identificar e gerenciar suas emoções no ambiente profissional.",
    tasks: [
      { id: "1-1", title: "Introdução à IE", completed: false },
      { id: "1-2", title: "Autoconhecimento", completed: false },
      { id: "1-3", title: "Empatia no trabalho", completed: false },
    ],
  },
  {
    id: "2",
    title: "Python para Análise de Dados",
    duration: "4 horas",
    level: "Intermediário",
    status: "in_progress" as const,
    category: "Hard Skills",
    description: "Domine as ferramentas essenciais de análise de dados com Python.",
    tasks: [
      { id: "2-1", title: "Introdução ao Pandas", completed: true },
      { id: "2-2", title: "Visualização com Matplotlib", completed: true },
      { id: "2-3", title: "Projeto prático", completed: false },
    ],
  },
  {
    id: "3",
    title: "Comunicação Assertiva",
    duration: "1.5 horas",
    level: "Iniciante",
    status: "completed" as const,
    category: "Soft Skills",
    description: "Desenvolva habilidades de comunicação clara e eficaz.",
    tasks: [
      { id: "3-1", title: "Fundamentos", completed: true },
      { id: "3-2", title: "Prática de feedback", completed: true },
      { id: "3-3", title: "Simulações", completed: true },
    ],
  },
  {
    id: "4",
    title: "Design Thinking Aplicado",
    duration: "3 horas",
    level: "Intermediário",
    status: "not_started" as const,
    category: "Criatividade",
    description: "Aprenda metodologias ágeis para resolver problemas complexos.",
    tasks: [
      { id: "4-1", title: "Empatia e definição", completed: false },
      { id: "4-2", title: "Ideação", completed: false },
      { id: "4-3", title: "Prototipagem", completed: false },
    ],
  },
];

export const mockProjects = [
  {
    id: "1",
    title: "Plataforma de Mentoria Comunitária",
    type: "Social",
    description: "Conecte jovens a mentores profissionais em comunidades carentes.",
    skills: ["Comunicação", "Liderança", "Organização"],
    difficulty: "Médio",
    duration: "3 meses",
    participants: 12,
  },
  {
    id: "2",
    title: "App de Reciclagem Inteligente",
    type: "Ambiental",
    description: "Desenvolva um aplicativo que gamifica a reciclagem urbana.",
    skills: ["Programação", "Design", "Sustentabilidade"],
    difficulty: "Avançado",
    duration: "4 meses",
    participants: 8,
  },
  {
    id: "3",
    title: "Alfabetização Digital para Idosos",
    type: "Educacional",
    description: "Ensine tecnologia básica para a terceira idade.",
    skills: ["Comunicação", "Empatia", "Paciência"],
    difficulty: "Fácil",
    duration: "2 meses",
    participants: 15,
  },
  {
    id: "4",
    title: "Horta Comunitária Urbana",
    type: "Ambiental",
    description: "Implemente hortas em espaços públicos da cidade.",
    skills: ["Organização", "Sustentabilidade", "Trabalho em equipe"],
    difficulty: "Médio",
    duration: "6 meses",
    participants: 20,
  },
  {
    id: "5",
    title: "Biblioteca Virtual Acessível",
    type: "Educacional",
    description: "Crie uma biblioteca digital com recursos de acessibilidade.",
    skills: ["Programação", "Design", "Pesquisa"],
    difficulty: "Avançado",
    duration: "5 meses",
    participants: 6,
  },
];

export const mockRecommendations = [
  {
    id: "1",
    type: "learning",
    title: "Continue seu módulo de Python",
    description: "Você está 60% completo! Apenas 1h30 para finalizar.",
    icon: "BookOpen",
    priority: "high",
  },
  {
    id: "2",
    type: "wellness",
    title: "Faça uma pausa",
    description: "Você está focado há 2 horas. Que tal um alongamento?",
    icon: "Heart",
    priority: "medium",
  },
  {
    id: "3",
    type: "project",
    title: "Novo projeto disponível",
    description: "App de Reciclagem Inteligente combina com suas skills.",
    icon: "Sparkles",
    priority: "medium",
  },
  {
    id: "4",
    type: "learning",
    title: "Módulo recomendado",
    description: "Comunicação Assertiva pode complementar suas soft skills.",
    icon: "Target",
    priority: "low",
  },
];

export const mockMoodHistory = [
  { date: "2025-01-15", mood: "Feliz", score: 5 },
  { date: "2025-01-16", mood: "Neutro", score: 3 },
  { date: "2025-01-17", mood: "Estressado", score: 2 },
  { date: "2025-01-18", mood: "Feliz", score: 4 },
  { date: "2025-01-19", mood: "Cansado", score: 3 },
  { date: "2025-01-20", mood: "Feliz", score: 5 },
  { date: "2025-01-21", mood: "Neutro", score: 3 },
];

export const mockWellnessTips = [
  {
    id: "1",
    title: "Respiração 4-7-8",
    description: "Inspire por 4s, segure por 7s, expire por 8s. Repita 4 vezes.",
    duration: "2 min",
    icon: "Wind",
  },
  {
    id: "2",
    title: "Pausa para Alongamento",
    description: "Levante-se e alongue braços, pescoço e pernas.",
    duration: "5 min",
    icon: "Move",
  },
  {
    id: "3",
    title: "Meditação Guiada",
    description: "Feche os olhos e foque na sua respiração.",
    duration: "10 min",
    icon: "Brain",
  },
  {
    id: "4",
    title: "Gratidão Diária",
    description: "Liste 3 coisas pelas quais você é grato hoje.",
    duration: "3 min",
    icon: "Heart",
  },
];
